# golangci-lint configuration for gotoon
# Documentation: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  go: '1.23.4'
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check imports formatting
    - misspell      # Check for misspelled words
    - revive        # Linting rules
    - gocritic      # Comprehensive Go linter
    - gocyclo       # Check cyclomatic complexity
    - gosec         # Security issues
    - copyloopvar   # Check for loop variable capture (replaces exportloopref)

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable:
      - shadow
    disable: []

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - dupl

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA1019:"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  show-stats: true
